#pragma once

#define CRISP_MOUSE_BUTTON_1			1
#define CRISP_MOUSE_BUTTON_2			2
#define CRISP_MOUSE_BUTTON_3			3
#define CRISP_MOUSE_BUTTON_4			4
#define CRISP_MOUSE_BUTTON_5			5
#define CRISP_MOUSE_BUTTON_LEFT			CRISP_MOUSE_BUTTON_1
#define CRISP_MOUSE_BUTTON_MIDDLE		CRISP_MOUSE_BUTTON_2
#define CRISP_MOUSE_BUTTON_RIGHT		CRISP_MOUSE_BUTTON_3